"""
SDC Django settings extension for SdcTest.

Generated by 'SdcTest' using SDC.

For more information on this file, see
https://simpledomcontrol.readthedocs.io/en/latest/
"""
import os
from urllib.parse import urlparse

from SdcTest.base_settings import *


def _parse_allowed_host(value):
    # ALLOWED_HOST is a comma-separated list of site URLs; entries without a scheme are read as https.
    urls = []
    for entry in value.split(','):
        entry = entry.strip()
        if entry:
            urls.append(urlparse(entry if '://' in entry else f'https://{entry}'))
    return urls


if not DEBUG:
    _hosts = _parse_allowed_host(os.environ.get('ALLOWED_HOST', ''))
    if not _hosts:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("Set the environment variable ALLOWED_HOST when DEBUG is False.")
    ALLOWED_HOSTS = [host.hostname for host in _hosts]
    CSRF_TRUSTED_ORIGINS = [f'{host.scheme}://{host.netloc}' for host in _hosts]
    _default_home_url = f'{_hosts[0].scheme}://{_hosts[0].netloc}'
else:
    ALLOWED_HOSTS = ['*']
    _default_home_url = 'http://127.0.0.1:8000'

if 'HOME_URL' not in locals():
    HOME_URL = os.environ.get('HOME_URL', _default_home_url)

if 'VERSION' not in locals():
    VERSION = 0.0

# Add daphne amd SDC packages to installed apps
# (https://docs.djangoproject.com/en/5.1/howto/deployment/asgi/daphne/)

INSTALLED_APPS = ['daphne'] + INSTALLED_APPS + ['channels', 'sdc_tools', 'sdc_user']

if 'INTERNAL_IPS' not in locals():
    INTERNAL_IPS = (
        '127.0.0.1',
    )

# DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

STATIC_ROOT = BASE_DIR / 'www/'

STATICFILES_DIRS = [BASE_DIR / "static", BASE_DIR / "node_modules"]

# Set ASGI root (https://docs.djangoproject.com/en/5.1/howto/deployment/asgi/daphne/)

ASGI_APPLICATION = 'SdcTest.asgi.application'

# Setup necessary template settings for SDC

TEMPLATES[0]["APP_DIRS"] = True
if BASE_DIR / "templates" not in TEMPLATES[0]["DIRS"]:
    TEMPLATES[0]["DIRS"].append(BASE_DIR / "templates")

if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [('redis', 6379)],
            },
        },
    }

if 'MEDIA_URL' not in locals():
    MEDIA_URL = '/media/'

if 'MEDIA_ROOT' not in locals():
    MEDIA_ROOT = BASE_DIR / 'media'

SERVER_CALL_VIA_WEB_SOCKET = False
MODEL_FORM_TEMPLATE = "elements/form.html"
LOGIN_CONTROLLER = 'sdc-login'
LOGIN_SUCCESS = '/'

JWT = {'secret': SECRET_KEY, 'algorithm': 'HS256', 'exp_delta_seconds': 3600}

"""
def sdc_user_get_queryset(user, action, obj):
    return user.is_authenticated
"""
SDC_USER_GET_QUERYSET = "sdc_user.models.sdc_user_get_queryset"

""""
def sdc_user_get_queryset(sdc_user_cls, user, action, ob
    if user.is_superuser:
        return sdc_user_cls.queryset.all()
    else:
        return sdc_user_cls.objects.filter(pk=user.pk)
"""
SDC_USER_IS_AUTHORISED = "sdc_user.models.sdc_user_is_authorised"
SDC_USER_FIELDS = "__all__"
SDC_USER_FIELDS_EXCLUDE = None

# E-mail credentials are read from the environment; never commit them.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = True
