# Generated by Django 5.0 on 2023-12-19 05:08

import django.db.models.deletion
import sdc_core.sdc_extentions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
            bases=(models.Model, sdc_core.sdc_extentions.models.SdcModel),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_test.author')),
            ],
            bases=(models.Model, sdc_core.sdc_extentions.models.SdcModel),
        ),
    ]
