# Generated by Django 5.2.8 on 2025-11-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdc_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SdcUser',
        ),
    ]
